# Generated by Django 3.2.12 on 2024-02-05 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.URLField(verbose_name='')),
                ('fullName', models.CharField(max_length=255)),
                ('job', models.CharField(choices=[], max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='')),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Enter a valid format phone number', regex='^(0|91)?[6-9][0-9]{8}')])),
                ('startDate', models.DateField(auto_now=True)),
                ('descriptionJob', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[], max_length=100)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Enter a valid format password', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!#%*?&]{8,20}')])),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
