# Generated by Django 3.2.12 on 2024-02-05 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20240205_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photos', models.JSONField()),
                ('roomType', models.CharField(choices=[('Single Bed', 'Single Bed'), ('Double Bed', 'Double Bed'), ('Double Superior', 'Double Superior'), ('Suite', 'Suite')], max_length=20)),
                ('roomNumber', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('offer', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3)),
                ('priceNight', models.DecimalField(decimal_places=2, max_digits=2, validators=[django.core.validators.MinValueValidator(50.0), django.core.validators.MaxValueValidator(200.0)])),
                ('discount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('cancellation', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked')], max_length=20)),
            ],
        ),
    ]
