# Generated by Django 3.2.12 on 2024-02-05 15:39

from django.db import migrations, models
import django.db.models.deletion
import polls.bookings


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('orderDate', models.DateField(auto_now_add=True)),
                ('check_in', models.DateField(validators=[polls.bookings.checkInHigherOrderDate])),
                ('hour_in', models.TimeField()),
                ('check_out', models.DateField(validators=[polls.bookings.checkOutHigherCheckIn])),
                ('hour_out', models.TimeField()),
                ('specialRequest', models.TextField(max_length=255)),
                ('status', models.CharField(choices=[('Check In', 'Check In'), ('Check Out', 'Check Out'), ('In Progress', 'In Progress')], default='Check In', max_length=20)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.room')),
            ],
        ),
    ]
