# Generated by Django 3.2.12 on 2024-02-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_id',
            new_name='room',
        ),
        migrations.AlterField(
            model_name='booking',
            name='specialRequest',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
