# Generated by Django 3.2.12 on 2024-02-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20240205_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room',
            new_name='room_id',
        ),
    ]
