# Generated by Django 3.2.12 on 2024-02-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_booking_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['room', 'specialRequest']},
        ),
    ]
