# Generated by Django 3.2.12 on 2024-02-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['room_id', 'specialRequest']},
        ),
    ]
