# Generated by Django 3.2.12 on 2024-02-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_booking_specialrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='specialRequest',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
