# Generated by Django 3.2.12 on 2024-02-05 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_booking_specialrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='priceNight',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(50.0), django.core.validators.MaxValueValidator(200.0)]),
        ),
    ]
